version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Maximum size of a log file
        max-file: "3"     # Maximum number of log files to keep


  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Maximum size of a log file
        max-file: "3"     # Maximum number of log files to keep





  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume:






# version: '3.8'

# services:
#   galleria_web:
#     build: ./galleria
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./galleria:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - DEBUG=1
#       - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
#     depends_on:
#       - galleria_db
#       - galleria_redis
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"

#   galleria2_web:
#     build: ./galleria2
#     command: python manage.py runserver 0.0.0.0:8001
#     volumes:
#       - ./galleria2:/app
#     ports:
#       - "8001:8001"
#     environment:
#       - DEBUG=1
#       - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
#     depends_on:
#       - galleria2_db
#       - galleria2_redis
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"

#   galleria_db:
#     image: postgres:13
#     volumes:
#       - postgres_data_galleria:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres

#   galleria2_db:
#     image: postgres:13
#     volumes:
#       - postgres_data_galleria2:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres

#   galleria_redis:
#     image: redis:6
#     ports:
#       - "6379:6379"

#   galleria2_redis:
#     image: redis:6
#     ports:
#       - "6380:6379"

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./galleria/static:/static/galleria
#       - ./galleria2/static:/static/galleria2
#     depends_on:
#       - galleria_web
#       - galleria2_web

# volumes:
#   postgres_data_galleria:
#   postgres_data_galleria2:
#   static_volume:
#   media_volume:
