# Generated by Django 4.2.7 on 2024-01-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userrelationship_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
        migrations.DeleteModel(
            name='UserRelationship',
        ),
    ]
