# Generated by Django 4.2.7 on 2024-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_follower_follower_name_following_following_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='custom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower_avi',
            field=models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='following',
            name='custom_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='following',
            name='following_avi',
            field=models.ImageField(blank=True, default='/meganfox.webp', null=True, upload_to=''),
        ),
    ]
