# Generated by Django 4.2.7 on 2024-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_post_user_avi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
