# Generated by Django 4.2.7 on 2024-01-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_customuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
