# Generated by Django 4.2.7 on 2024-01-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_followrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower_avi',
        ),
    ]
