# Generated by Django 4.2.7 on 2024-01-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_follower_follower_avi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_avi',
        ),
    ]
