# Generated by Django 4.2.7 on 2024-01-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_post_user_avi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
