# Generated by Django 4.2.7 on 2024-01-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_post_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
