# Generated by Django 4.2.7 on 2024-02-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='product',
            new_name='post',
        ),
    ]
