# Generated by Django 5.0.2 on 2024-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isSlice',
            field=models.BooleanField(default=False),
        ),
    ]
