# Generated by Django 5.0.1 on 2024-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0035_post_isslice"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_tutorial",
            field=models.BooleanField(default=False),
        ),
    ]
