# Generated by Django 5.0.1 on 2024-10-04 11:00

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0036_customuser_is_tutorial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[base.validators.file_size],
            ),
        ),
    ]
