# Generated by Django 5.0.1 on 2024-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_alter_post_image_alter_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="album",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
