# Generated by Django 5.1.2 on 2024-10-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_expopushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avi',
            field=models.URLField(blank=True, default='/avatar.png', null=True),
        ),
    ]
