# Generated by Django 5.1.2 on 2024-10-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_customuser_avi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avi',
            field=models.URLField(blank=True, default='https://izpkijnmscmbolveusoo.supabase.co/storage/v1/object/public/Galleria/pfp/avatar-19-svgrepo-com.png', null=True),
        ),
    ]
