# Generated by Django 5.1.4 on 2025-02-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_customuser_avi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_connections',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
