# Generated by Django 4.2.7 on 2024-01-26 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notifice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifice',
            new_name='Notice',
        ),
    ]
