# Generated by Django 4.2.7 on 2024-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notifice_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow Request'), ('like', 'Like Notification'), ('comment', 'Comment Notification')], default='like', max_length=20),
        ),
    ]
